### ISSUE TITLE
Startup error on Ubuntu 22.04

### ISSUE THREAD

**Issue by stancosti** [ClarkFieseln/IPRadar2ForLinux#1]
Any idea what I'm missing?

INFO {IPRadar2} [main] entering main()..
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/.local/bin/ipradar2", line 8, in <module>
    sys.exit(main())
  File "/.local/lib/python3.10/site-packages/IPRadar2/IPRadar2.py", line 32, in main
    ui = MyMainWindow()
  File "/.local/lib/python3.10/site-packages/IPRadar2/mainAppWindow.py", line 296, in __init__
    index = self.comboBoxInterface.getCurrentIndex()
AttributeError: 'QComboBox' object has no attribute 'getCurrentIndex'. Did you mean: 'setCurrentIndex'?

**Comment by stancosti** [comment]
I found-out that I can bypass the error by setting INTERFACE in the config file to empty. This allows DUMPCAP to populate the dropdown/combo.

The next challenge is to populate the interface list with all values. It appears DUMPCAP requires sudo to retrieve all interfaces, otherwise it will default to the ones the current user has permissions to access.

Any suggestions what to do next?

**Comment by stancosti** [comment]
> I found-out that I can bypass the error by setting INTERFACE in the config file to empty. This allows DUMPCAP to populate the dropdown/combo.
> 
> The next challenge is to populate the interface list with all values. It appears DUMPCAP requires sudo to retrieve all interfaces, otherwise it will default to the ones the current user has permissions to access.
> 
> Any suggestions what to do next?

The current user requires execute rights on the DUMPCAP process. 
      > sudo chmod +x /usr/bin/dumpcap

The combo populates with the correct interfaces and all errors are resolved after running this command.

Finally, I want to thank you for offering this software. Great idea! I'm impressed with your work! 

Regards,
Costi S.

**Comment by ClarkFieseln** [comment]
Hi Costi,
sorry, I am pretty busy right now, and was planning to check your issue this weekend.
I  am glad you solved the problem(s) in between.
Quick feedback:
- I will check if there is an issue with the INTERFACE parameter 
- regarding DUMPCAP, I suspect you might have missed some steps in point 4) of the READ_ME.txt file:
  https://github.com/ClarkFieseln/IPRadar2ForLinux/blob/main/READ_ME.txt
  (but I will check that too. You can try undoing your chmod and instead following the steps there to see if it works).
- Thanks for your last comment! I am glad that this helps people.
  I also believe that the idea is great, but to be honest I just wrote a "straightforward" code, taking a lot of shortcuts and
  investing as less time as needed (I don't have much time for hobbies). Please take that into account.
  The quality of the code could be highly improved to make it more "professional", but then the readability
  would suffer and it would be more difficult to understand for beginners (which most of the people are...including me :).

Regards,
Clark

**Comment by ClarkFieseln** [comment]
I corrected a bug in the selection of the INTERFACE (thanks for writing the issue!).
I also improved the READ_ME.txt and created a new Tag = 0.0.4. Also the PyPI project is updated.
